## DEPLOYMENT FILE PHPMyAdmin - Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  namespace: project-1
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin/phpmyadmin:latest
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: mysql-ser
            - name: PMA_PORT
              value: "3306"
            - name: MYSQL_ROOT_PASSWORD
              value: password
          volumeMounts:
            - name: sessions-volume
              mountPath: /sessions
      volumes:
        - name: sessions-volume
          emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  namespace: project-1
spec:
  selector:
    app: phpmyadmin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

